---

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install ntp
  package: name=ntp state=present

- name: Create ntp config file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart ntp
  
- name: Start ntp
  service: name={{ ntp_service_name }} enabled=yes state=started
